const RoleActionTypes = {
    FETCH_ROLES_START: 'FETCH_ROLES_START',
    FETCH_ROLES_SUCCESS: 'FETCH_ROLES_SUCCESS',
    FETCH_ROLES_FAILURE: 'FETCH_ROLES_FAILURE',
}

export default RoleActionTypes;

