const MATCH_DATA = [
    {
      id: 1,
      date: 'THRUSDAY, FEBRUARY 20',
      routeName: 'red',
      items: [
        {
          id: 1,
          FirstTeam: 'RED',
          FirstTeamFinalScore: '1',
          FirstTeamScore: 'Nathan Jeong',
          FirstTeamAssist: 'Nathan Jeong',
          SecondTeam: 'YELLOW',
          SecondTeamFinalScore: '2',
          SecondTeamScore: 'Nathan Jeong',
          SecondTeamAssist: 'Nathan Jeong', 
        },
        {
          id: 2,
          FirstTeam: 'RED',
          FirstTeamFinalScore: '1',
          FirstTeamScore: 'Nathan Jeong',
          FirstTeamAssist: 'Nathan Jeong',
          SecondTeam: 'YELLOW',
          SecondTeamFinalScore: '2',
          SecondTeamScore: 'Nathan Jeong',
          SecondTeamAssist: 'Nathan Jeong', 
        },
        {
          id: 3,
          FirstTeam: 'RED',
          FirstTeamFinalScore: '1',
          FirstTeamScore: 'Nathan Jeong',
          FirstTeamAssist: 'Nathan Jeong',
          SecondTeam: 'YELLOW',
          SecondTeamFinalScore: '2',
          SecondTeamScore: 'Nathan Jeong',
          SecondTeamAssist: 'Nathan Jeong', 
        },
        {
          id: 4,
          FirstTeam: 'RED',
          FirstTeamFinalScore: '1',
          FirstTeamScore: 'Nathan Jeong',
          FirstTeamAssist: 'Nathan Jeong',
          SecondTeam: 'YELLOW',
          SecondTeamFinalScore: '2',
          SecondTeamScore: 'Nathan Jeong',
          SecondTeamAssist: 'Nathan Jeong', 
        },
        {
          id: 5,
          FirstTeam: 'RED',
          FirstTeamFinalScore: '1',
          FirstTeamScore: 'Nathan Jeong',
          FirstTeamAssist: 'Nathan Jeong',
          SecondTeam: 'YELLOW',
          SecondTeamFinalScore: '2',
          SecondTeamScore: 'Nathan Jeong',
          SecondTeamAssist: 'Nathan Jeong', 
        },
        {
          id: 6,
          FirstTeam: 'RED',
          FirstTeamFinalScore: '1',
          FirstTeamScore: 'Nathan Jeong',
          FirstTeamAssist: 'Nathan Jeong',
          SecondTeam: 'YELLOW',
          SecondTeamFinalScore: '2',
          SecondTeamScore: 'Nathan Jeong',
          SecondTeamAssist: 'Nathan Jeong', 
        }
      ]
    },
    {
      id: 2,
      date: 'THRUSDAY, FEBRUARY 27',
      routeName: 'blue',
      items: [
        {
          id: 10,
          FirstTeam: 'RED',
          FirstTeamFinalScore: '1',
          FirstTeamScore: 'Nathan Jeong',
          FirstTeamAssist: 'Nathan Jeong',
          SecondTeam: 'YELLOW',
          SecondTeamFinalScore: '2',
          SecondTeamScore: 'Nathan Jeong',
          SecondTeamAssist: 'Nathan Jeong', 
        },
        {
          id: 11,
          FirstTeam: 'RED',
          FirstTeamFinalScore: '1',
          FirstTeamScore: 'Nathan Jeong',
          FirstTeamAssist: 'Nathan Jeong',
          SecondTeam: 'YELLOW',
          SecondTeamFinalScore: '2',
          SecondTeamScore: 'Nathan Jeong',
          SecondTeamAssist: 'Nathan Jeong', 
        },
        {
          id: 12,
          FirstTeam: 'RED',
          FirstTeamFinalScore: '1',
          FirstTeamScore: 'Nathan Jeong',
          FirstTeamAssist: 'Nathan Jeong',
          SecondTeam: 'YELLOW',
          SecondTeamFinalScore: '2',
          SecondTeamScore: 'Nathan Jeong',
          SecondTeamAssist: 'Nathan Jeong', 
        },
        {
          id: 13,
          FirstTeam: 'RED',
          FirstTeamFinalScore: '1',
          FirstTeamScore: 'Nathan Jeong',
          FirstTeamAssist: 'Nathan Jeong',
          SecondTeam: 'YELLOW',
          SecondTeamFinalScore: '2',
          SecondTeamScore: 'Nathan Jeong',
          SecondTeamAssist: 'Nathan Jeong', 
        },
        {
          id: 14,
          FirstTeam: 'RED',
          FirstTeamFinalScore: '1',
          FirstTeamScore: 'Nathan Jeong',
          FirstTeamAssist: 'Nathan Jeong',
          SecondTeam: 'YELLOW',
          SecondTeamFinalScore: '2',
          SecondTeamScore: 'Nathan Jeong',
          SecondTeamAssist: 'Nathan Jeong', 
        },
        {
          id: 15,
          FirstTeam: 'RED',
          FirstTeamFinalScore: '1',
          FirstTeamScore: 'Nathan Jeong',
          FirstTeamAssist: 'Nathan Jeong',
          SecondTeam: 'YELLOW',
          SecondTeamFinalScore: '2',
          SecondTeamScore: 'Nathan Jeong',
          SecondTeamAssist: 'Nathan Jeong', 
        },
        {
          id: 16,
          FirstTeam: 'RED',
          FirstTeamFinalScore: '1',
          FirstTeamScore: 'Nathan Jeong',
          FirstTeamAssist: 'Nathan Jeong',
          SecondTeam: 'YELLOW',
          SecondTeamFinalScore: '2',
          SecondTeamScore: 'Nathan Jeong',
          SecondTeamAssist: 'Nathan Jeong', 
        },
        {
          id: 17,
          FirstTeam: 'RED',
          FirstTeamFinalScore: '1',
          FirstTeamScore: 'Nathan Jeong',
          FirstTeamAssist: 'Nathan Jeong',
          SecondTeam: 'YELLOW',
          SecondTeamFinalScore: '2',
          SecondTeamScore: 'Nathan Jeong',
          SecondTeamAssist: 'Nathan Jeong', 
        }
      ]
    }
  ];
  
  export default MATCH_DATA;
  