const MemberActionTypes = {
    FETCH_MEMBERS_START: 'FETCH_MEMBERS_START',
    FETCH_MEMBERS_SUCCESS: 'FETCH_MEMBERS_SUCCESS',
    FETCH_MEMBERS_FAILURE: 'FETCH_MEMBERS_FAILURE',
    POST_MEMBERS_START: 'POST_MEMBERS_START',
    POST_MEMBERS_SUCCESS: 'POST_MEMBERS_SUCCESS',
    POST_MEMBERS_FAILURE: 'POST_MEMBERS_FAILURE',
    PUT_MEMBERS_START: 'PUT_MEMBERS_START',
    PUT_MEMBERS_SUCCESS: 'PUT_MEMBERS_SUCCESS',
    PUT_MEMBERS_FAILURE: 'PUT_MEMBERS_FAILURE',
    SET_CURRENT_MEMBERID: 'SET_CURRENT_MEMBERID'
}

export default MemberActionTypes;

