const RecordActionTypes = {
    FETCH_RECORDS_START: 'FETCH_RECORDS_START',
    FETCH_RECORDS_SUCCESS: 'FETCH_RECORDS_SUCCESS',
    FETCH_RECORDS_FAILURE: 'FETCH_RECORDS_FAILURE',
    POST_RECORDS_START: 'POST_RECORDS_START',
    POST_RECORDS_SUCCESS: 'POST_RECORDS_SUCCESS',
    POST_RECORDS_FAILURE: 'POST_RECORDS_FAILURE',
    PUT_RECORDS_START: 'PUT_RECORDS_START',
    PUT_RECORDS_SUCCESS: 'PUT_RECORDS_SUCCESS',
    PUT_RECORDS_FAILURE: 'PUT_RECORDS_FAILURE',
    ADD_RECORD: 'ADD_RECORD',
    ADD_ROW_TO_RECORD: 'ADD_ROW_TO_RECORD',
    TOGGLE_RECORD_HIDDEN: 'TOGGLE_RECORD_HIDDEN'
}

export default RecordActionTypes;

