const LeagueActionTypes = {
    TOGGLE_LEAGUE_HIDDEN: 'TOGGLE_LEAGUES_HIDDEN',
    FETCH_LEAGUES_START: 'FETCH_LEAGUES_START',
    FETCH_LEAGUES_SUCCESS: 'FETCH_LEAGUES_SUCCESS',
    FETCH_LEAGUES_FAILURE: 'FETCH_LEAGUES_FAILURE'
}

export default LeagueActionTypes;