const LeagueActionTypes = {
    TOGGLE_LEAGUE_HIDDEN: 'TOGGLE_LEAGUES_HIDDEN',
    FETCH_LEAGUES_START: 'FETCH_LEAGUES_START',
    FETCH_LEAGUES_SUCCESS: 'FETCH_LEAGUES_SUCCESS',
    FETCH_LEAGUES_FAILURE: 'FETCH_LEAGUES_FAILURE',
    FETCH_LEAGUE_STANDINGS_START: 'FETCH_LEAGUE_STANDINGS_START',
    FETCH_LEAGUE_STANDINGS_SUCCESS: 'FETCH_LEAGUE_STANDINGS_SUCCESS',
    FETCH_LEAGUE_STANDINGS_FAILURE: 'FETCH_LEAGUE_STANDINGS_FAILURE',
    FETCH_LEAGUE_MATCHRECORDS_START: 'FETCH_LEAGUE_MATCHRECORDS_START',
    FETCH_LEAGUE_MATCHRECORDS_SUCCESS: 'FETCH_LEAGUE_MATCHRECORDS_SUCCESS',
    FETCH_LEAGUE_MATCHRECORDS_FAILURE: 'FETCH_LEAGUE_MATCHRECORDS_FAILURE', 
    SET_CURRENT_LEAGUE: 'SET_CURRENT_LEAGUE'
}

export default LeagueActionTypes;