const MatchActionTypes = {
    FETCH_MATCHES_START: 'FETCH_MATCHES_START',
    FETCH_MATCHES_SUCCESS: 'FETCH_MATCHES_SUCCESS',
    FETCH_MATCHES_FAILURE: 'FETCH_MATCHES_FAILURE',
    POST_MATCHES_START: 'POST_MATCHES_START',
    POST_MATCHES_SUCCESS: 'POST_MATCHES_SUCCESS',
    POST_MATCHES_FAILURE: 'POST_MATCHES_FAILURE',
    PUT_MATCHES_START: 'PUT_MATCHES_START',
    PUT_MATCHES_SUCCESS: 'PUT_MATCHES_SUCCESS',
    PUT_MATCHES_FAILURE: 'PUT_MATCHES_FAILURE',
    DELETE_MATCHES_START: 'DELETE_MATCHES_START',
    DELETE_MATCHES_SUCCESS: 'DELETE_MATCHES_SUCCESS',
    DELETE_MATCHES_FAILURE: 'DELETE_MATCHES_FAILURE',
    SET_SELECTED_MATCHID: 'SET_SELECTED_MATCHID',
    SET_MATCH_HOME_TEAM: 'SET_MATCH_HOME_TEAM',
    SET_MATCH_AWAY_TEAM: 'SET_MATCH_AWAY_TEAM',
    SET_MATCH_LOCATION: 'SET_MATCH_LOCATION',
    ADD_NEW_MATCH: 'ADD_NEW_MATCH'
}

export default MatchActionTypes;

