const MatchActionTypes = {
    FETCH_MATCHES_START: 'FETCH_MATCHES_START',
    FETCH_MATCHES_SUCCESS: 'FETCH_MATCHES_SUCCESS',
    FETCH_MATCHES_FAILURE: 'FETCH_MATCHES_FAILURE'
}

export default MatchActionTypes;